apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    description: Some description
  labels:
    PGPASSWORD: you_thought_so?
  name: some-test-job
spec:
  template:
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - /bin/sh somescript.sh > test.sql
        image: alpine
        imagePullPolicy: IfNotPresent
        name: some-test-job
        resources:
          limits:
            cpu: 1
            memory: 32Mi
        securityContext:
          privileged: false
      restartPolicy: Never
      terminationGracePeriodSeconds: 0
